export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function MainLayout({ children }) {
    return (
      <html
      lang='es'
      suppressHydrationWarning
    >
      <head>
      </head>
      <body>
        {children}
      </body>
    </html>
    )
  }
  