import "primereact/resources/themes/lara-light-cyan/theme.css";
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css'
import '../../style/globals.scss'
import DashboardLayout from "@/layout/layout";
import { PrimeReactProvider } from "primereact/api";
import { UserProvider } from "@/state-management/react-context/user.context";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function ProtectedLayout({ children }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <head></head>
      <body>
        <PrimeReactProvider>
          <UserProvider>
            <DashboardLayout>{children}</DashboardLayout>
          </UserProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
