import "primereact/resources/themes/lara-light-cyan/theme.css";
import DashboardLayout from "@/layout/layout";
import { PrimeReactProvider } from "primereact/api";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function ProtectedLayout({ children }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <head></head>
      <body>
        <PrimeReactProvider>
          <DashboardLayout>{children}</DashboardLayout>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
