import "primereact/resources/themes/lara-light-cyan/theme.css";
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css'
import '../../style/layout/layout.scss'
import { PrimeReactProvider } from "primereact/api";
// import { UserProvider } from "@/state-management/react-context/user.context";
import { LayoutProvider } from '../../layout/context/layoutcontext';
import Layout from '../../layout/layout';
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function ProtectedLayout({ children }) {
  return (
    <html
      lang='es'
      suppressHydrationWarning
    >
      <head></head>
      <body>
        <PrimeReactProvider>
            <LayoutProvider>
              <Layout>{children}</Layout>
            </LayoutProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
