import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div>
      {/* <div>topbar</div>
      <div>sidebar</div> */}
      <div>{children}</div>
      {/* <div>footer</div> */}
    </div>
  );
}
