import { Inter } from "next/font/google";
import "./globals.scss";
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import MainLayout from "@/app/layout";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const request = () => {
  fetch("http://localhost:8200/usuarios", {})
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body>
          {children}
        </body>
      </PrimeReactProvider>
    </html>
  );
}
