import { Inter } from "next/font/google";
import HeadlessDemo from "./app-sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="w-full h-screen flex flex-column">
      <div className="flex flex-column bg-gray-300 w-full h-4rem">
        TOPBAR
      </div>
      <div className="flex w-full">
        <div className="sidebar">Sidebar</div>
        <div className="flex-grow-1">{children}</div>
      </div>
      {/* <div>topbar</div> */}
      {/* <HeadlessDemo /> */}
      
      {/* <div>footer</div> */}
    </div>
  );
}
